# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reflector_ihm.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(658, 594)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(10000, 10000))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_Bottom = QtGui.QGridLayout()
        self.gridLayout_Bottom.setObjectName(_fromUtf8("gridLayout_Bottom"))
        self.gridLayout_Ctrl = QtGui.QGridLayout()
        self.gridLayout_Ctrl.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_Ctrl.setObjectName(_fromUtf8("gridLayout_Ctrl"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.StepDownButton = QtGui.QPushButton(self.centralwidget)
        self.StepDownButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/rewind.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StepDownButton.setIcon(icon)
        self.StepDownButton.setObjectName(_fromUtf8("StepDownButton"))
        self.gridLayout_5.addWidget(self.StepDownButton, 1, 1, 1, 1)
        self.OpenFileButton = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.OpenFileButton.setFont(font)
        self.OpenFileButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/eject.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenFileButton.setIcon(icon1)
        self.OpenFileButton.setObjectName(_fromUtf8("OpenFileButton"))
        self.gridLayout_5.addWidget(self.OpenFileButton, 1, 0, 1, 1)
        self.StepUpButton = QtGui.QPushButton(self.centralwidget)
        self.StepUpButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/image/forward.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StepUpButton.setIcon(icon2)
        self.StepUpButton.setObjectName(_fromUtf8("StepUpButton"))
        self.gridLayout_5.addWidget(self.StepUpButton, 1, 2, 1, 1)
        self.gridLayout_Ctrl.addLayout(self.gridLayout_5, 7, 2, 1, 1)
        self.ScanSlider = QtGui.QSlider(self.centralwidget)
        self.ScanSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ScanSlider.setObjectName(_fromUtf8("ScanSlider"))
        self.gridLayout_Ctrl.addWidget(self.ScanSlider, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ScanLabel = QtGui.QLabel(self.centralwidget)
        self.ScanLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ScanLabel.setObjectName(_fromUtf8("ScanLabel"))
        self.horizontalLayout_2.addWidget(self.ScanLabel)
        self.TimeLabel = QtGui.QLabel(self.centralwidget)
        self.TimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeLabel.setObjectName(_fromUtf8("TimeLabel"))
        self.horizontalLayout_2.addWidget(self.TimeLabel)
        self.NbPointsLabel = QtGui.QLabel(self.centralwidget)
        self.NbPointsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NbPointsLabel.setObjectName(_fromUtf8("NbPointsLabel"))
        self.horizontalLayout_2.addWidget(self.NbPointsLabel)
        self.gridLayout_Ctrl.addLayout(self.horizontalLayout_2, 2, 2, 3, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_Ctrl.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_Bottom.addLayout(self.gridLayout_Ctrl, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_Bottom, 1, 0, 1, 1)
        self.gridLayout_Top = QtGui.QGridLayout()
        self.gridLayout_Top.setObjectName(_fromUtf8("gridLayout_Top"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_Graph = QtGui.QGridLayout()
        self.gridLayout_Graph.setObjectName(_fromUtf8("gridLayout_Graph"))
        self.horizontalLayout.addLayout(self.gridLayout_Graph)
        self.gridLayout_Top.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.TypeBinarSlider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TypeBinarSlider.sizePolicy().hasHeightForWidth())
        self.TypeBinarSlider.setSizePolicy(sizePolicy)
        self.TypeBinarSlider.setMaximum(1)
        self.TypeBinarSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TypeBinarSlider.setObjectName(_fromUtf8("TypeBinarSlider"))
        self.horizontalLayout_3.addWidget(self.TypeBinarSlider)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.SeuilSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.SeuilSpinBox.setAccelerated(True)
        self.SeuilSpinBox.setMaximum(255)
        self.SeuilSpinBox.setObjectName(_fromUtf8("SeuilSpinBox"))
        self.verticalLayout_2.addWidget(self.SeuilSpinBox)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.FilterSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.FilterSpinBox.setObjectName(_fromUtf8("FilterSpinBox"))
        self.verticalLayout_2.addWidget(self.FilterSpinBox)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setLineWidth(1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.ReflectorLenLCD = QtGui.QLCDNumber(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.ReflectorLenLCD.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ReflectorLenLCD.setFont(font)
        self.ReflectorLenLCD.setNumDigits(10)
        self.ReflectorLenLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.ReflectorLenLCD.setObjectName(_fromUtf8("ReflectorLenLCD"))
        self.verticalLayout_2.addWidget(self.ReflectorLenLCD)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self.ReflectorMidLCD = QtGui.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ReflectorMidLCD.setFont(font)
        self.ReflectorMidLCD.setNumDigits(10)
        self.ReflectorMidLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.ReflectorMidLCD.setObjectName(_fromUtf8("ReflectorMidLCD"))
        self.verticalLayout_2.addWidget(self.ReflectorMidLCD)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_Top.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_Top, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Reflector Analyser", None))
        self.ScanLabel.setText(_translate("MainWindow", "Scan", None))
        self.TimeLabel.setText(_translate("MainWindow", "Num Cycle", None))
        self.NbPointsLabel.setText(_translate("MainWindow", "Nombre de points", None))
        self.label_3.setText(_translate("MainWindow", "Scan :", None))
        self.label_4.setText(_translate("MainWindow", "Type de Binarisation :", None))
        self.label_6.setText(_translate("MainWindow", "Statique", None))
        self.label_5.setText(_translate("MainWindow", "Dynamique", None))
        self.label.setText(_translate("MainWindow", "Seuil de Binarisation :", None))
        self.label_2.setText(_translate("MainWindow", "Coefficient de Filtrage :", None))
        self.label_7.setText(_translate("MainWindow", "Longueur du Réflecteur Mesurée :", None))
        self.label_8.setText(_translate("MainWindow", "Milieu du Réflecteur :", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))

import reflector_ihm_rc
